/calibrate_position:
  ros__parameters:
    time_space: 100
    date_length: 100
    # data_dir: "../../../../src/calibrate_position/data.txt"
    # data_dir: "package://ros2_galaxy_camera/data.txt"
    armors_topic: /detector/armors
    gimbal_frame: gimbal_link
    world_frame: odom
